// Use https://finicky-kickstart.now.sh to generate basic configuration
// Learn more about configuration options: https://github.com/johnste/finicky/wiki/Configuration

// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  options: {
    // Hide the finicky icon from the top bar. Default: false
    hideIcon: true, 
    // Check for update on startup. Default: true
    checkForUpdate: true,
  },

  //Default to latest active window
  defaultBrowser: {
    name: "Brave Browser",
  },
  handlers: [
    {
      // Open links at inovex.de in Brave Work
      match: /.*\.*inovex\.de/,
      browser: {
        name: "Brave Browser",
        profile: "Default",
      }
    },
    {
      // Open links in Slack in Brave Work
      match: ({ opener }) =>
        opener.bundleId === "com.tinyspeck.slackmacgap",
      browser: {
        name: "Brave Browser",
        profile: "Default",
      }
    },
    {
      // Open links an netrtl.com in Brave Customer
      match: /.*\.*netrtl\.com/,
      browser: {
        name: "Brave Browser",
        profile: "Profile 3",
      }
    },
    {
      // Open links in Teams in Brave Customer
      match: ({ opener }) =>
        opener.bundleId === "com.microsoft.teams",
      browser: {
        name: "Brave Browser",
        profile: "Profile 3",
      }
    },
    {
      // Open links in Outlook in Brave Customer
      match: ({ opener }) =>
        opener.bundleId === "com.microsoft.Outlook",
      browser: {
        name: "Brave Browser",
        profile: "Profile 3",
      }
    },
    {
      // Open links in Discord in Brave Privat
      match: ({ opener }) =>
        opener.bundleId === "com.hnc.Discord",
      browser: {
        name: "Brave Browser",
        profile: "Profile 1",
      }
    },
  ]
}

