// Use https://finicky-kickstart.now.sh to generate basic configuration
// Learn more about configuration options: https://github.com/johnste/finicky/wiki/Configuration

// Generated by Finicky Kickstart
// Save as ~/.finicky.js

export default {
  options: {
    // Hide the finicky icon from the top bar. Default: false
    hideIcon: true,
    // Check for update on startup. Default: true
    checkForUpdate: true,
  },

  //Default to latest active window
  defaultBrowser: {
    name: "Brave Browser",
  },
  handlers: [
    {
      // Open links at inovex.de in Brave Work
      match: /.*\.*inovex\.de/,
      browser: {
        name: "Brave Browser",
        profile: "Default",
      }
    },
    {
      // Open links in Slack in Brave Work
      match: () =>
        ["com.tinyspeck.slackmacgap"].includes(opener.bundleId),
      browser: {
        name: "Brave Browser",
        profile: "Default",
      }
    },
    {
      // Open links on netrtl.com in Brave Customer
      match: /.*\.*netrtl\.com/,
      browser: {
        name: "Brave Browser",
        profile: "Profile 3",
      }
    },
    {
      // Open links in Teams and Outlook in Brave Customer
      match: () =>
        ["com.microsoft.teams", "com.microsoft.teams2", "com.microsoft.Outlook"].includes(opener.bundleId),
      browser: {
        name: "Brave Browser",
        profile: "Profile 3",
      }
    },
    {
      // Open links in Discord and Mail in Brave Privat
      match: () =>
          ["com.hnc.Discord", "com.apple.mail"].includes(opener.bundleId),
      browser: {
        name: "Brave Browser",
        profile: "Profile 1",
      }
    },
  ]
}

